In [1]:
#这个不是感知机 这个是梯度感知机
import numpy as np

In [324]:
def f(x):
    result = []
    results = []
    for x_i in x:
        for x_j in x_i:
            if x_j>0:
                result.append(1)
            else:
                result.append(0)
        results.append(result)
    return np.array(results)

In [325]:
# test all function here
print (f([[0.3,4,5]]))

[[1 1 1]]


In [349]:
def predict_y(input_vec,weights,bias):
    temp = np.dot(input_vec,weights.transpose())
    print (temp)
    temp = temp.transpose()+bias
    print (temp)
    return f(temp)
    

In [350]:
input_vec = np.random.randint(1,10,size=(3,4))
weights = np.ones((1,input_vec.shape[1]))

In [351]:
print (input_vec)

[[3 7 1 6]
 [1 4 4 9]
 [5 4 2 6]]


In [352]:
print (type(weights))

<class 'numpy.ndarray'>


In [353]:
bias = 0
print (predict_y(input_vec,weights,bias))
print ()

[[ 17.]
 [ 18.]
 [ 17.]]
[[ 17.  18.  17.]]
[[1 1 1]]



In [331]:

def train(input_vec,target,weights,bias,alpha,max_iter):
    for i in range(max_iter):
        p_y = predict_y(input_vec,weights,bias)
        delta = target-p_y#1*n
        delta_w = np.dot(np.dot(alpha,delta),input_vec)
        delta_b = np.dot(alpha,delta)
        weights = weights+delta_w
        bias = bias+delta_b
    return weights,bias
    


In [332]:
target = np.random.randint(0,1,size=(1,input_vec.shape[0]))
target

array([[0, 0, 0]])

In [333]:
alpha = 0.01
MAX_ITER = 100
input_vec = np.array([[1,1], [0,0], [1,0], [0,1]])
print (input_vec.shape)
target = np.array([[1, 0, 0, 0]])
print (type(target))
print (target.shape)
weights = np.ones((1,input_vec.shape[1]))
bias = np.zeros((1,input_vec.shape[0]))
bias = 0
weights,bias = train(input_vec,target,weights,bias,alpha,MAX_ITER)
print (weights,bias)
    

(4, 2)
<class 'numpy.ndarray'>
(1, 4)
[[ 0.5  0.5]] [[ 0.   0.  -0.5 -0.5]]
